services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-prd:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile.production
    container_name: go-app-prd
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    env_file:
      - .env
    working_dir: /app

volumes:
  postgres-data-prd:
