# Dockerfile.production

# Build stage
FROM golang:1.23 as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .

# Runtime stage
FROM debian:bullseye-slim
WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/main .

# Ensure the binary is executable
RUN chmod +x ./main

# Expose port if necessary
EXPOSE 8080

# Run the binary
CMD ["./main"]
