version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app-shiftwave
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/tmp
    working_dir: /app

volumes:
  postgres-data:
